config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  get 'sign_in' => 'sessions#new', as: 'sign_in'
  get 'sign_out' => 'sessions#destroy', as: 'sign_out'
  get 'sign_up' => 'users#new', as: 'sign_up'
  get 'incoming/create'
  
  post :incoming, to: 'incoming#create'

  resources :users, except: :index
  resources :sessions
  resources :password, only: [:new, :edit]
  post 'reset_password' => 'password#create'
  post 'update_password' => 'password#update'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks

  def to_s
    # custom
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :topics
  before_create { generate_token(:auth_token) }

  validates :email, presence: true
  # validates :password, presence: true#, confirmation: true
  #validates :password_confirmation, presence: true

  def send_password_reset
    generate_token(:reset_token)
    self.reset_token_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver_now
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  # def create_password_reset_token
  #   self.reset_token = SecureRandom.hex 128
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #force_ssl

  def current_user
    @current_user ||= User.find_by(auth_token: cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    # {sender: user.email, subject: topic.title, 'body-plain': 'http://example.org'}

    puts "INCOMING PARAMS HERE: #{params}"
      user = User.find_by(email: params[:sender])
      title = params[:subject]
      topic = Topic.find_by(title: title)

      User.create(email: params[:sender]) unless user

      topic.bookmarks.create(
        url: params['body-plain']) 

      head 200
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user
      user.send_password_reset
      redirect_to root_url, notice: 'Email sent with instructions.'
    else
      redirect_to root_url, notice: 'User not found.'
    end
  end

  def edit
    @user = User.find_by!(reset_token: params[:id])
  end

  def update
    @user = User.find_by!(reset_token: params[:id])
    if @user.password_reset_sent_at > 2.hours.ago
      redirect_to new_password_path, alert: 'Password reset has expired.'
    elsif @user.update_attributes(params[:user])
      redirect_to root_url, notice: 'Password has been updated'
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end

      redirect_to root_url, notice: 'Signed in!'
    else
      flash.now.alert = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url, notice: 'Signed out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: 'Signed up!'
    else
      flash[:error] = 'Invalid email or password'
      render 'new'
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocmarks", root_path %></li>
      
    <div class="pull-right user-info">
      <% if current_user.present? %>
        <%= current_user.email %>
        <%= link_to session_path(session), method: :delete, class: 'btn btn-primary btn-sm' do %>
          <span class="glyphicon glyphicon-log-out"></span>
        <% end %>
      <% else %>
        <%= link_to "Sign In", new_session_path %>
        <%= link_to "Sign Up", new_user_path %>
      <% end %>
    </div>
    </ul>
          
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

<%= yield %>

</body>
</html>

app/views/password/edit.html.erb
<h1>Password Reset</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @user, password_path(params[:id]) do |f| %>

      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, '', class: 'form-control', placeholder: "Enter new password" %>
      </div>

      <div class="form-group">
        <%= f.submit "Update Password", class: 'btn btn-success', data: { disable_with: 'Submitting...' } %>
      </div>

    <% end %>
    
  </div>
</div>

app/views/password/new.html.erb
<h1>Password Reset</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_tag reset_password_path do %>

      <div class="form-group">
        <%= label_tag :email %>
        <%= text_field_tag :email, '', class: 'form-control', placeholder: "Enter email address" %>
      </div>

      <div class="form-group">
        <%= submit_tag "Submit", class: 'btn btn-success', data: { disable_with: 'Submitting...' } %>
      </div>

    <% end %>
    
  </div>
</div>

app/views/password/reset.html.erb
<h1>Email sent</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @user do |f| %>
      
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control', placeholder: "Enter email address" %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
      </div>

      <div class="form-group">
        <%= f.submit "Submit", class: 'btn btn-success', data: { disable_with: 'Submitting...' } %>
      </div>

    <% end %>
    
  </div>
</div>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Blockmarks</h1>
  <p>Blocmarks stores your bookmarks via email. Start topics. Add bookmarks. Read later.</p>
  <p>
      <%= link_to "Sign In", new_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Create</h2>
    <p>Blocmarks allows you to store all your bookmarks.</p>
  </div>
  <div class="col-md-4">
    <h2>Contribute</h2>
    <p>Blocmarks allows you to group by topic.</p>
  </div>
  <div class="col-md-4">
    <h2>Organize</h2>
    <p>Blocmarks allows you to add via email.</p>
  </div>
</div>